localdb:
  image: postgres:11.2
  ports:
    - '5432:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=local
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=local

testdb:
  image: postgres:11.2
  ports:
    - '5433:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=test
